language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- flake8
- pytest
- "./.travis_run.sh --dry-run"
deploy:
  provider: script
  script: "./.travis_run.sh"
  on:
    branch: master
    repo: Linaro/qa-reports-known-issues
